// Global state management
const state = {
    firms: [],
    cities: [],
    currentFirm: null,
    searchMatches: [],
    currentSort: 'none',
    viewMode: 'map',
    gmailTickets: [],
    ticketError: null,
    ticketRefreshInterval: null,
    activeFirmId: null,
    resolvedTicketIds: new Set(),
    dismissedTicketIds: new Set(),
    canvas: null,
    ctx: null,
    camera: { x: 0, y: 0, zoom: 1 },
    isDragging: false,
    dragStart: { x: 0, y: 0 },
    isGlobeDragging: false,
    hoveredFirm: null,
    animationFrame: null,
    mapSvg: null,
    mapG: null,
    mapCountries: null,
    mapStates: null,
    mapCounties: null,
    mapCities: null,
    mapBubblesGroup: null,
    mapGraticule: null,
    mapSphere: null,
    mapBounds: null,
    mapProjection: null,
    mapZoom: null,
    mapRotation: { lambda: 0, phi: 0 },
    mapBaseScale: 1,
    mapScale: 1,
    mapDimensions: { width: 0, height: 0 },
    mapZoomTransform: d3.zoomIdentity,
    lastStaticRender: {
        lambda: null,
        phi: null,
        scale: null,
        countiesVisible: null
    }
};
