export const NEWS_FIRM_NAMES = [
    'Blackstone (NYS: BX)',
    'Apollo Asset Management (NYS: APO)',
    'Kohlberg Kravis Roberts (NYS: KKR)',
    'The Carlyle Group (NAS: CG)',
    'Janus Capital Group',
    'Baillie Gifford',
    'TPG (NAS: TPG)',
    'CVC Capital Partners (AMS: CVC)',
    'Hauck Aufhuser Lampe Private Markets',
    'Elyan Partners',
    'Ardian',
    'Bain Capital',
    'Thoma Bravo',
    'Poalim Equity',
    'Partners Group (SWX: PGHN)',
    'HPS Investment Partners',
    'AMP Capital Investors',
    'Silver Lake',
    'Hellman & Friedman',
    'General Atlantic',
    'Advent International',
    'Hg',
    'Vista Equity Partners',
    'Carlyle AlpInvest',
    'Permira',
    'Clearlake Capital Group',
    'Apax Partners',
    'Bridgepoint Group (UK) (LON: BPT)',
    'Warburg Pincus',
    'Sixth Street Partners',
    'H.I.G. Europe',
    'HarbourVest Horizon',
    'Lexington Partners',
    'H.I.G. Capital',
    'Coatue Management',
    'Stone Point Capital',
    'Bayside Capital',
    'H.I.G. Growth Partners',
    'CICC Capital',
    'Adams Street Partners',
    'SoftBank Investment Advisers',
    'TA Associates Management',
    'Sands Capital',
    'Investcorp',
    'Yongjin Group',
    'New Mountain Capital',
    'PAG',
    'Veritas Capital Fund Management',
    'Fortress Investment Group',
    '3i Group (LON: III)',
    'Cinven',
    'Genstar Capital',
    'GTCR',
    'Platinum Equity',
    'BC Partners',
    'Bridgepoint Group',
    'Francisco Partners',
    'Summit Partners',
    'Eurazeo (PAR: RF)',
    'Centerbridge Partners',
    'Centricus',
    'Boyu Capital',
    'JAB Holding Company',
    'Nordic Capital',
    'Antin Infrastructure Partners (PAR: ANTIN)',
    'L Catterton',
    'CriteriaCaixa',
    'TJC (Private Equity)',
    'Generation Investment Management',
    'PSG',
    'CDH Investments',
    'Astorg',
    'Fullerton Financial Holdings',
    'Valor Equity Partners',
    'Bregal Sagemount',
    'Dragoneer Investment Group',
    'LKCM Headwater Investments',
    'Pasaca Capital',
    'The Plymouth Group',
    'TowerBrook Capital Partners',
    'MSD Partners',
    'Northleaf Capital Partners',
    'Accel-KKR',
    'Providence Equity Partners',
    'Charlesbank Capital Partners',
    'Cutwater Asset Management',
    'EQT Private Capital Asia',
    'Alpha Wave Global',
    'TCV',
    'Primavera Capital Group',
    'Vitruvian Partners',
    'OMERS Private Equity',
    'Harvest Partners',
    'K1 Investment Management',
    'Audax Private Equity',
    'InfraVia Capital Partners',
    'AEA Growth',
    'AEA Investors',
    'Maysaffron',
    'Tata Capital',
    'Alpine Investors',
    'Patria Private Equity Trust',
    'I3CP Holdings',
    'OrbiMed',
    'RCP Advisors',
    'Abry Partners',
    'Siguler Guff',
    'Triton Partners',
    'Actis',
    'Kelso & Company',
    'Montagu Private Equity',
    'Waterland Private Equity Investments',
    'Foresight Group (LON: FSG)',
    'Madison Dearborn Partners',
    'One Equity Partners',
    'Stephens',
    'Thomas H. Lee Partners',
    'Addor Capital',
    'CF Private Equity',
    'Battery Ventures',
    'HOPU (Hong Kong)',
    'RRJ Capital',
    'Brighton Jones Investment Partners',
    'Inflexion Private Equity Partners',
    'Oak Hill Capital',
    'Investindustrial',
    'Yuexiu Financial Holdings',
    'Affinity Equity Partners',
    'Hahn & Company',
    'Institutional Investment Partners Denmark',
    'The Abraaj Group',
    'Sycamore Partners',
    'Parthenon Capital Partners',
    'Tobin Capital',
    'Welsh, Carson, Anderson & Stowe',
    'Aquiline (New York)',
    'Hony Capital',
    'Kingdom Holding Company (SAU: 4280)',
    'Oakley Capital',
    'Levine Leichtman Capital Partners',
    'Invus Financial Advisors',
    '3G Capital',
    'The Riverside Company',
    'RedBird Capital Partners',
    'STG Partners',
    'Great Hill Partners',
    'Capza',
    'SWEN Capital Partners',
    'CapVest Partners',
    'Sofina (BRU: SOF)',
    'Golden Gate Capital',
    'Maj Invest',
    'Pacific Equity Partners',
    'Cercano Management',
    'Tikehau Investment Management',
    'Arsenal Capital Partners',
    'Novacap',
    'Riverstone Holdings',
    '777 Partners',
    'Gryphon Investors',
    'MidOcean Partners',
    'NB Capital Solutions',
    'Premji Invest',
    'Springs Capital',
    'Sycamore Ventures',
    'The Chartered Group',
    'The Invus Group',
    'Yunfeng Capital',
    'TPG Newbridge',
    'Arlington Capital Partners',
    'Court Square',
    'ArcLight Capital Partners',
    'JMI Equity',
    'HQ Capital',
    'Kartesia',
    'ARCHIMED',
    'Verdane',
    'Performance Equity Management',
    'Co-Stone Capital',
    'Shumway Capital',
    'Marlin Equity Partners',
    'Cohen & Murphy Capital Partners',
    'Sentinel Capital Partners',
    'Gridiron Capital',
    'The Cynosure Group',
    'Meridiam',
    'Ridgemont Equity Partners',
    'Corsair Capital',
    'Bregal Unternehmerkapital',
    'Main Street Advisors',
    'Fisher Lynch Capital',
    'AJ Capital & Investments',
    'Everstone Capital',
    'Goldman Sachs Growth Equity',
    'Harbert Management',
    'Littlejohn & Co.',
    'Somerset Capital Partners',
    'Trive Capital',
    'Trustbridge Partners',
    'Naxicap Partners',
    'Omnes Capital',
    'Pollen Street Capital',
    'Pamplona Capital Management',
    'Equistone Partners Europe',
    'Trilantic North America',
    'Maranon Capital',
    'CapMan (HEL: CAPMAN)',
    'WestBridge Capital (San Mateo)',
    'Spectrum Equity',
    'LLR Partners',
    'Lightyear Capital',
    'Odyssey Investment Partners',
    'Apex Capital Management',
    'Freeman Spogli',
    'China Minsheng Investment Group',
    'Keensight Capital',
    'Main Capital Partners',
    'CapitalG',
    'Centurium Capital',
    'FIMI Opportunity Funds',
    'Generation PE',
    'J.F. Lehman & Company',
    'SSG Capital Management',
    'Teachers Venture Growth',
    'HGGC',
    'Crosspoint Capital Partners',
    '17Capital',
    'Stripes',
    'Atlas Investment Management',
    'Medley Partners Management',
    'Leeds Equity Partners',
    'Shamrock Capital Advisors',
    'AE Industrial Partners',
    'BGH Capital',
    'STIC Investments (KRX: 026890)',
    'Incline Equity Partners',
    'Riverwood Capital',
    'WestCap (New York)',
    'Aurora Capital Partners',
    'BDC Capital',
    'FTV Capital',
    'Orchid Asia Group Management',
    'Quadrant Private Equity',
    'Trivest Partners',
    'Seidler Equity Partners',
    'Castik Capital',
    'Charterhouse Capital Partners',
    'Rivean Capital',
    'Seven2',
    'Ufenau Capital Partners',
    'Greater Sum Ventures',
    'Azimuth Capital Management (PE)',
    'One Madison Group',
    'SummitView Capital',
    'Andera Partners',
    'NewMargin Ventures',
    'SBI Holdings (TKS: 8473)',
    'Dansk Ejerkapital',
    'Maxis Capital',
    'Kline Hill Partners',
    'Pamlico Capital',
    'Siris Capital Group',
    'BV Investment Partners',
    'Flexstone Partners',
    'Level Equity',
    'Silversmith Capital Partners',
    'Lovell Minnick Partners',
    'Birch Hill Equity Partners',
    'Cathay Capital Private Equity',
    'ChrysCapital',
    'Gemspring Capital',
    'Lead Edge Capital',
    'Lurra Capital',
    'Navis Capital Partners',
    'Serent Capital',
    'Tamarind Capital',
    'The Ascent Group',
    'Motive Partners',
    'Turn/River Capital',
    'Cove Hill Partners',
    'Edmond de Rothschild Private Equity',
    'Affinity Partners (Miami)',
    'Tybourne Capital Management',
    'Livingbridge',
    'BlackFin Capital Partners',
    'FSN Capital',
    'Groupe HLD',
    'Latour Capital',
    'Montefiore Investment',
    'NORD Holding',
    'Siparex Group',
    'Tailwind Capital',
    'Evia Capital Partners',
    'Brinley Partners',
    'Waud Capital Partners',
    'H.I.G. HealthBridge Partners',
    'Starr Private Equity Partners',
    'Haveli Investments',
    'NMS Capital Group',
    'OceanSound Partners',
    'Thompson Street Capital Partners',
    'Bow River Capital',
    'JLL Partners',
    'Anchor Equity Partners',
    'Brighton Park Capital',
    'M-One Capital',
    'Armira Beteiligungen',
    'Bertram Capital',
    'Affirma Capital',
    'Rubicon Technology Partners',
    'SAIF Partners',
    'SEB Private Equity',
    'VMS Asset Management',
    'SkyKnight Capital',
    'Graham Partners',
    'Tinicum',
    'Emerging Investment Partners',
    'Pacific Avenue Capital Partners',
    'Kylla Corporate Transactions',
    'Tresmares Capital',
    'Centre Lane Partners',
    'Baring Vostok Capital Partners',
    'Crescent Point Group',
    'Monterro',
    'Cressey & Company',
    'First Plaza Group Trust',
    'Deutsche Private Equity',
    'Elvaston Capital Management',
    'Marcol Group',
    'Novator Partners',
    'NXMH',
    'Peninsula Capital (London)',
    'Bure Equity (STO: BURE)',
    'Imperial Capital Group',
    'NewSpring Capital',
    'Palladium Equity Partners',
    'ONCAP',
    'Prysm Capital',
    'Gauge Capital',
    'H&Q Asia Pacific',
    'Industry Capital',
    'Weston Presidio',
    'Sumeru Equity Partners',
    'BGF (Financial Services)',
    'Fiera Comox Partners',
    'Clairvest Group (TSE: CVG)',
    'Luminate Capital Partners',
    'Recognize Partners',
    'Vestar Capital Partners',
    'Deutsche Beteiligungs (ETR: DBAN)',
    'MML Capital Partners',
    'Liberty Strategic Capital',
    'WP Global Partners',
    'The Raine Group',
    'ZMC',
    'Ethos Capital (Boston)',
    'Gilde Healthcare',
    'The Edgewater Fund',
    'Ampersand (Massachusetts)',
    'Creador',
    'Desjardins Capital',
    'DTCP',
    'Five Elms Capital',
    'Golden Brick Capital',
    'Helios Investment Partners',
    'Hennessy Capital Group',
    'L1 Technology',
    'Multiples Alternate Asset Management',
    'Spinnaker Trust',
    'The Xander Group',
    'True North',
    'Kingswood Capital Management',
    'Adelis Equity Partners',
    'Argenthal',
    'Gilde Equity Management',
    'Perwyn Advisors',
    'Indigo Partners',
    'Fondaction',
    'Metric Capital Partners',
    'Avesi Partners',
    'Paragon Partners',
    'Trilantic Europe',
    'Oceanpine Capital',
    'Morehead Capital',
    'Axcel Management',
    'WestSummit Capital',
    'Chicago Pacific Founders',
    'Fortissimo Capital',
    'Norwest Equity Partners',
    'Mercia Asset Management (LON: MERC)',
    'Kensington Capital Partners',
    'The Chernin Group',
    'Capvis',
    'Integrum (Asset Management)',
    'CMC Capital Partners',
    'Dover Madison Capital Management',
    'Greenbelt Capital Management',
    'PeakSpan Capital',
    'Smash Capital',
    'Susquehanna Growth Equity',
    'Wells Fargo Strategic Capital',
    'Mainsail Partners',
    'CDC International Capital',
    'Turenne Groupe',
    'Epiris',
    'TZP Group',
    'Auburn Hill Capital',
    'Gulf Capital',
    'TimeX Capital',
    'LL Funds',
    'JKL Partners',
    'Polaris Capital Group',
    'Simplicity',
    'Argos.',
    'Chequers Capital',
    'Nextalia SGR',
    'Enlightenment Capital',
    'Sverica Capital Management',
    'Hosen Capital',
    'Brynwood Partners',
    'Africinvest',
    'GenNx360 Capital Partners',
    'Bowmark Capital',
    'Synova Capital',
    'CIVC Partners',
    'Further Global Capital Management',
    'GreyLion',
    'Preservation Capital Partners',
    'NexPhase Capital',
    'True Wind Capital Management',
    'Declaration Partners',
    'Banneker Partners',
    'AGIC Group',
    'Edison Partners',
    'Morgan Stanley Private Equity Asia',
    'Avenir Growth Capital',
    'Potentia Capital',
    'Apiary Capital',
    'Martis Capital Management',
    'Glade Brook Capital Partners',
    'Resurgens Technology Partners',
    'Sunstone Partners',
    'Diversis Capital',
    'Clearview Capital',
    'WestView Capital Partners',
    'Goldfinch Partners',
    'EW Healthcare Partners',
    'PFM Health Sciences',
    'Tensile Capital Management',
    '50T',
    'AEI Capital',
    'Asia Green Fund',
    'August Capital',
    'Baltisse',
    'Concentric Equity Partners',
    'EdgeStone Capital Partners',
    'Envision Capital',
    'Everpine Capital',
    'Finaccess Capital',
    'Hidden Harbor Capital Partners',
    'Joffre Capital',
    'Mercuria Investment Company',
    'One Peak Partners',
    'Pemba Capital Partners',
    'Peterson Partners',
    'Public Pension Capital',
    'Sageview Capital',
    'Sol Global Investments (CNQ: SOL)',
    'Tan Capital Partners',
    'Trinity Hunt Partners',
    'Zinqular Group',
    'Allianz X',
    'Azimut Libera Impresa',
    'Crescent Capital Partners (Sydney)',
    'Post Road Group',
    'Mason Wells',
    'Clarion Capital Partners',
    'Sandton Capital Partners',
    'Gimv (BRU: GIMB)',
    'Elevation Partners',
    'Frontier Growth',
    'LongRange Capital',
    'Tower Arch Capital',
    'Middle East Financial Investment (SAU: 4346)',
    'Private Capital Research',
    'GrowthCurve Capital',
    'Premier Partners',
    'Align Capital Partners',
    'Entrepreneurial Equity Partners',
    'Bracket Capital',
    'Truelink Capital',
    'BNP Paribas Development',
    'EMH Partners',
    'FCM Frederic Capital Management',
    'Headway Capital Partners',
    'KLAR Partners',
    'UI Investissement',
    'Gaocheng Capital',
    'Primus Capital',
    'Bow Wave Capital Management',
    'Updata Partners',
    'Accelerated Venture Partners',
    'CLAUSEN Consulting & Invest',
    'Ethos Private Equity',
    'Rockbridge Growth Equity',
    'Volition Capital',
    'Kora Management',
    'Tritium Partners',
    'ForgeLight',
    'Avance Investment Management',
    'Corten Capital',
    'Transformation Capital',
    'Carrick Capital Partners',
    'BlackRock Private Equity Partners',
    'Spring Mountain Capital',
    'Horizon Capital (Kyiv)',
    'Horizon Capital (London)',
    'Main Street Capital (NYS: MAIN)',
    'Sorenson Capital',
    'NovaQuest Capital Management',
    'Atlantic Street Capital',
    'Granite Partners (Saint Cloud)',
    'DC Capital Partners',
    'L Squared Capital Partners',
    'Perry Creek Capital',
    'Guidepost Growth Equity',
    'Abris Capital Partners',
    'Arka Capital',
    'ECS Capital',
    'Kennet Partners',
    'MBO+',
    'Parcom Capital',
    'Muller & Monroe Asset Management',
    'Pender Growth Fund (TSX: PTF)',
    'Herkules Capital',
    'OpenGate Capital',
    'Origami Capital Partners',
    'Anchorage Capital Partners',
    'Canyon Bridge Capital Partners',
    'Capital Square Partners',
    'Digital Alpha Advisors',
    'Evolution Equity Partners',
    'Hermitage Capital',
    'Infinity Group',
    'Ironbridge Capital',
    'Mission Holdings',
    'Paceline Equity Partners',
    'SMC Capital China',
    'TDM Growth Partners',
    'Transom Capital Group',
    'Housatonic Partners',
    'Capiton',
    'Albion Investors',
    'Mountaingate Capital',
    'Iron Point Partners',
    'Satori Capital',
    'Longreach Group',
    '123 Investment Managers',
    '21 Invest (Veneto)',
    'Fremman Capital',
    'GPF Partners (Spain)',
    'Magnum Capital Industrial Partners',
    'Project A Ventures',
    'KY Private Equity Fund',
    'Xingfu Investment Management',
    'Bedford Funding Capital Management',
    'Bregal Milestone',
    'Invision Capital',
    'Kotak Private Equity Group',
    'Steadfast Equity',
    'Stonehenge Partners',
    'The Yucaipa Companies',
    'Alta Park Capital',
    'Princeton Equity Group',
    'Capitol Meridian Partners',
    'Zebra Capital Partners',
    'Leumi Partners',
    'Blum Capital Partners',
    'Phoenix Equity Partners',
    'True.',
    'GRO Capital',
    'Composition Capital',
    'Novalpina Capital',
    'SEEK Investments',
    'Delta-v Capital',
    'Mountain Capital Management',
    'Acura Capital',
    'Baird Capital',
    'Kharis Capital',
    'Adagia Partners',
    'GMA Capital',
    'Mediterrania Capital Partners',
    'CBPE Capital',
    'Lone View Capital',
    'Guosen H&S',
    'FrontRange Capital Partners',
    'Sagewind Capital',
    'Maxburg Capital Partners',
    'Radian Capital',
    'Five Points Capital',
    'Volpi Capital',
    'Huron Capital',
    'TT Capital Partners',
    'Linse Capital',
    'Corbel Capital Partners',
    'NorthEdge Capital',
    'Gallant Capital',
    'Advantage Investment Partners',
    'Alpha Leonis Partners',
    'American Pacific Group',
    'Lake Street Capital Partners (Chicago)',
    'Nexa Equity',
    'Ripplewood Advisors',
    'Blue Star Innovation Partners',
    'O2 Investment Partners',
    'Renaissance Partners (Italy)',
    'Enterprise Investors',
    'Invision (Zug)',
    'Atlantic Bridge Capital',
    'Avedon Capital Partners',
    'Cinco Capital',
    'DTCP Growth',
    'IdiCo',
    'Oxy Capital',
    'Ventech (Paris)',
    'The CID Group',
    'Ironview Capital Management',
    'Merit Capital Partners',
    'Axon Partners Group (MAD: APG)',
    'Heritage Group (US)',
    'Aldrich Capital Partners',
    'Capital Croissance',
    'Pavilion Capital',
    'Argosy Private Equity',
    'Baring Private Equity Partners India',
    'Mercato Partners',
    'SGT Capital',
    'Weatherford Capital',
    'Godspeed Capital',
    'Crest Rock Partners',
    'E&F Private Equity',
    'CapStreet (Private Equity)',
    'Scottish Equity Partners',
    'Maven Capital Partners UK',
    'Virgo Investment Group',
    'M/C Partners',
    'ThinCats',
    'Ten Coves Capital',
    'Hivest Capital Partners',
    'Sovereigns Capital',
    'Peninsula Capital Partners',
    'GEC',
    'Dominus Capital',
    'Trimaran Capital Partners',
    'Invictus Growth Partners',
    'Finback Investment Partners',
    'Atlas Merchant Capital',
    'Vantage Capital',
    'YFM Equity Partners',
    'Clearhaven Partners',
    'China Merchants China Direct Investments',
    'Ace Equity Partners',
    'AFV Partners',
    'AID Partners (HKG: 8088)',
    'Apax Digital Growth',
    'Archerman Capital',
    'Asia Partners',
    'Asia-IO Partners',
    'Build Capital Partners',
    'Celadon Partners',
    'Claret Capital Partners',
    'ClearVue Partners',
    'CMIA Capital Partners',
    'Falcata Capital',
    'Felicity Global Capital',
    'FGA Partners',
    'Forebright Capital',
    'Franchise Equity Partners',
    'Fulcrum Venture India',
    'Glisco Partners',
    'Goanna Capital',
    'Greyhound Capital',
    'Inverness Graham',
    'J17 Ventures',
    'Kilmer Group',
    'Levant Capital',
    'Lionsgate-invest',
    'Long Ridge Equity Partners',
    'Morgan Stanley Expansion Capital',
    'Multiplier Capital',
    'MVM Partners',
    'OMERS Growth Equity',
    'Pamoja Capital',
    'Pangeo Capital',
    'Stonebridge Capital',
    'Strattam Capital',
    'The Sputnik Group',
    'Westcap Management',
    'ZX Ventures.'
];