export const NEWS_FIRM_NAMES = [
    'Blackstone (NYS: BX)',
    'Apollo Asset Management (NYS: APO)',
    'Kohlberg Kravis Roberts (NYS: KKR)',
    'The Carlyle Group (NAS: CG)',
    'Janus Capital Group',
    'Baillie Gifford',
    'TPG (NAS: TPG)',
    'CVC Capital Partners (AMS: CVC)',
    'Hauck Aufhuser Lampe Private Markets',
    'Elyan Partners',
    'Ardian',
    'Bain Capital',
    'Thoma Bravo',
    'Poalim Equity',
    'Partners Group (SWX: PGHN)',
    'HPS Investment Partners',
    'AMP Capital Investors',
    'Silver Lake',
    'Hellman & Friedman',
    'General Atlantic',
    'Advent International',
    'Hg',
    'Vista Equity Partners',
    'Carlyle AlpInvest',
    'Permira',
    'Clearlake Capital Group',
    'Apax Partners',
    'Bridgepoint Group (UK) (LON: BPT)',
    'Warburg Pincus',
    'Sixth Street Partners',
    'H.I.G. Europe',
    'HarbourVest Horizon',
    'Lexington Partners',
    'H.I.G. Capital',
    'Coatue Management',
    'Stone Point Capital',
    'Bayside Capital',
    'H.I.G. Growth Partners',
    'CICC Capital',
    'Adams Street Partners',
    'SoftBank Investment Advisers',
    'TA Associates Management',
    'Sands Capital',
    'Investcorp',
    'Yongjin Group',
    'New Mountain Capital',
    'PAG',
    'Veritas Capital Fund Management',
    'Fortress Investment Group',
    '3i Group (LON: III)'
];
